### ISSUE TITLE
info: also works with 1820

### ISSUE THREAD

**Issue by FlorianHeigl** [dkolasinski/hp1920s-backup-script#1]
Hi,

I just successfully used the script today with OfficeConnect 1820s.
First to backup a "template" switch and deploy the config on another one after factory resetting it.
I don't know how to post to a HTML form (nor Perl), otherwise (or if the combination turns out very simple) I'd go after two features:

* config upload (i suppose that'd also make sense for you)
* ssl cert generation and toggling between http/https modes

I think that is all that's needed to get the next big step in automating those.
Do you know if the more current 1850's have the same config system?

I'll also give it a shot with 1810s and report back for that.

**Comment by dkolasinski** [comment]
I know this is an old comment. Sorry for not noticing it. I currently do not have access to any of HP 18XX. And the 1920s I support are in production use and in remote location, so I`m unable to test config upload.

Currently, I have Aruba InstantOn (1930?). And it won't work because, as far as I remember, it uses encryption at the JavaScript level.

**Comment by FlorianHeigl** [comment]
Hey, I also don't have access to them anymore :-)
It was nonetheless useful, thanks for your reply!
